import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card-list-craftsman',
  templateUrl: './card-list-craftsman.component.html',
  styleUrl: './card-list-craftsman.component.scss'
})
export class CardListCraftsmanComponent {

  @Input() craftsmanData:any = {};

  // Used for the tackBy for each star generated by the ngFor in card-top-craftsman.componenet.html
  starId(index: number, star: any): number {
    return star.id;
  }

  stars:any[] = [
    {
      id: "star-1",
      fill: "0%"
    },
    {
      id: "star-2",
      fill: "0%"
    },
    {
      id: "star-3",
      fill: "0%"
    },
    {
      id: "star-4",
      fill: "0%"
    },
    {
      id: "star-5",
      fill: "0%"
    }
  ];
}
