import { Component } from '@angular/core';
import { CardTopCraftsmanService } from '../card-top-craftsman.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {

  allData: any[] = [];
  topCraftsmansData:any[] = [];

  constructor(private craftsmanService:CardTopCraftsmanService) {}
  async ngOnInit():Promise<void> {
    this.allData = await this.craftsmanService.getDataCrafstman();
    this.topCraftsmansData = this.allData.filter((craftsman) => craftsman.top == true);
  }

  // Used for the tackBy for each top craftsman card generated by the ngFor in home.componenet.html
  craftsmanId(index: number, craftsman: any): string {
    return ("top"+craftsman.id);
  }
}
